### ISSUE TITLE
HTTP 403 Forbidden when trying to upload to Flickr

### ISSUE THREAD

**Issue by NguyenMatthieu** [mono/f-spot#16]
Raised on Ubuntu as https://bugs.launchpad.net/ubuntu/+source/f-spot/+bug/1335877

On June 27th, Flickr decided to switch all their API URLs to HTTPS-only. The FlickrNet API, prior to version 3.13, was using HTTP only to connect to the Flickr API. As a result, the Flickr Export is broken.

**Comment by decriptor** [comment]
I just updated Flickrnet to 3.17. It seems to work for me now. I'm going to close this, but if it still isn't work please reopen this issue.
