### ISSUE TITLE
DllNotFoundException: libgtk-win32-2.0-0.dll

### ISSUE THREAD

**Issue by NguyenMatthieu** [mono/f-spot#36]
Under some systems (Gentoo, Mageia 5), users have been facing a DllNotFoundException: libgtk-win32-2.0-0.dll issue.

    line 133:  Mono: DllImport attempting to load: 'libgtk-x11-2.0.so.0'.
    line 136:  Mono: DllImport loaded library 'libgtk-x11-2.0.so.0'.
    ...
    line 927:  Mono: DllImport attempting to load: 'libgtk-win32-2.0-0.dll'.
    lines 928..237 error loading library with variations on libgtk-win32 location
    line 938:  Mono: DllImport unable to load library 'libgtk-win32-2.0-0: cannot open shared object file: No such file or directory'.
    line 939..949 repeat of above errors
    line 950:  System.TypeInitializationException: An exception was thrown by the type initializer for GtkBeans.Builder ---> System.DllNotFoundException: libgtk-win32-2.0-0.dll
     followed by exception backtrace without filenames or lines
    line 963:  Mono: DllImport unable to load library 'libgtk-win32-2.0-0: cannot open shared object file: No such file or directory'.
    line 964:  Mono: DllImport searching in: 'libgtk-x11-2.0.so.0' ('libgtk-x11-2.0.so.0').

This issue is caused by the fact that in the f-spot bin folder (and then in the runtime directory), gtk-sharp-beans.dll is copied without its gtk-sharp-beans.dll.config. This happens with versions of gtk-sharp-beans prior to 2.14, where the DLLs were installed in the GAC, and some symlinks were missing from  /usr/lib/mono/gtk-sharp-beans-2.0, that f-spot uses to copy the gtk-sharp-beans locally.

Required gtk-sharp-beans version needs to be bumped to 2.14

**Comment by ostroffjh** [comment]
The only version of gtk-sharp-beans on Gentoo is currently 2.14.0.  My best guess is that the version in the gac is left over from an earlier install that was not removed on upgrade.  However, even in /usr/lib/gtk-sharp-beans, there is only a dll and mdb, no config.  I'll manually run through the install process to see if it gets dropped or is never produced.

**Comment by NguyenMatthieu** [comment]
I mean to do the same (build from package). Issue was opened so that we actually do track the problem until it's resolved. Mageia still bundles 2.13.92.

**Comment by ostroffjh** [comment]
It looks to me like the source package (2.14.0) does produce the .dll.config file, but does not install it.  I don't see Gentoo dropping or filtering anything.

**Comment by NguyenMatthieu** [comment]
HAHAHA.
https://github.com/mono/gtk-sharp-beans/commit/6565cb4bb04b923e50765ce7244224cd8b7387de
ok. this commit comes *after* the gtk-sharp-beans 2.14.0 release tag. And has never been included in any subsequent release. So @decriptor: the only reason you have the .config in the lib dir is that your distro probably bundled the "latest from git" instead of "actual release". Even 2.14.0 does not copy the file over.
How do we move forward here? While prompting distros to update to version 2.14.0 is acceptable, I don't think a prompt to "install latest git" is. Especially since on our side, we make checks based on particular versions, so we have no way of saying "this is the right 2.14.0". My feeling is that a new release of gtk-sharp-beans is required, if only to include this change.

**Comment by ostroffjh** [comment]
Thanks for finding this - at least we have an explanation.  For Gentoo, adding that patch alone can be done as a patch release, and I'll file a bug for it.  They do prefer an upstream fix, but are likely to accept it as a patch if upstream is just waiting for the  next release.

**Comment by NguyenMatthieu** [comment]
I see that on the tree, there actually was a commit to make a 2.14.1 that includes the .config:

https://github.com/mono/gtk-sharp-beans/commit/e2fb365a7032c3bff8157e64820c85b046421107

However, there never was a tag or release in a "git" sense...

**Comment by decriptor** [comment]
Since gtk-sharp-beans is a short term thing and will no longer be needed with gtk-sharp3 I wonder if for the time being we should just include gtk-sharp-beans (and possibly gio-sharp) in f-spot. It'll be removed once we go to gtk-sharp3.

**Comment by NguyenMatthieu** [comment]
@decriptor: Not sure that would be the best approach. Means we have to update the build scripts so that they build the project (similarly to Hyena and taglib-sharp, I suppose), as well as update all the csproj references to point to "the DLL we put in `external`". Especially if this is supposed to be temporary, that seems like a lot of work just to ensure a proper version.
However, getting the gtk-sharp-beans team to create a git release 2.14.1, I understand it is just a matter of creating a tag, and adding a couple of clicks in github to link the release to the tag.
Re: gtk-sharp3, that's probably another topic altogether :p

**Comment by ostroffjh** [comment]
My first question is how long will it be until f-spot can use gtk-sharp3 (and how long until gtk-sharp-3 has a production release)?  I suppose we could do a beta or test release relying on the beta or pre-release of gtk-sharp-beans.

For the current version, could we put in some explicit test looking for the .config file, and pop up an appropriate warning if not found - so it doesn't just give the not found error?  As a temporary fix, could we make a copy of the .config file available?  The build does produce the .config file - it just doesn't install it.

**Comment by decriptor** [comment]
I'm still thinking it might be worth the effort to bring gtk-sharp-beans and gio-sharp into the code base. Not as externals/git submodules, but just copying the code. I'm more than happy to do the heavily lifting since that is actually how it used to be and I removed them. I think the amount of effort to bring them in will be far simpler than the amount of effort it'll take to get all distros onto the "right" version :(

Part of the reason is both are essentially dead projects. gtk-sharp-beans was just a stop-gap, but gtk-sharp2 was never improved further. gio-sharp is now part of gtk-sharp3.

As for gtk-sharp3... Since the banshee project now depends on it and they have a GSOC project as well, I'm hoping that there'll be a stable release eventually (sooner than later). If anyone wants to grab the gtk3 branch and play with it you are welcome to, but it isn't ready yet.

**Comment by decriptor** [comment]
ok, I think I figure out why this is doing what it's doing. I believe that the gtk-sharp-beans.dll.config file is simply missing.

**Comment by decriptor** [comment]
Ok, I've now included the code directly f-spot as of commit 9b33366b

**Comment by NguyenMatthieu** [comment]
@decriptor "I believe the gtk-sharp-beans.dll.config file is simply missing" <-- that's actually the whole point of the thread :).

**Comment by decriptor** [comment]
@NguyenMatthieu in all fairness it was 1:30ish am for me. Things we maybe a little blurry ;)

**Comment by NguyenMatthieu** [comment]
@decriptor :). Important thing is the issue is closed :)
