### ISSUE TITLE
Build errors w/Debian, solved by setting TargetFrameworkVersion to v4.5

### ISSUE THREAD

**Issue by Yetangitu** [mono/f-spot#56]
When building on Debian (sid, using mono 4.2.1.102) a host of build errors are produced:

```
   CSC: error CS0518: The predefined type `System.Object' is not defined or imported
   CSC: error CS0518: The predefined type `System.(lots-of-other-types)' is not defined or imported
   ...
```

These errors can be avoided by setting TargetFrameworkVersion to v4.5 in the relevant _.csproj_ files. The affected files are:

```
/external/flickrnet/FlickrNet/FlickrNet.csproj
/external/mono-addins/Mono.Addins/Mono.Addins.csproj
/external/mono-addins/Mono.Addins.Setup/Mono.Addins.Setup.csproj
/external/mono-addins/Mono.Addins.Gui/Mono.Addins.Gui.csproj
```

As it is not clear as to whether this error only occurs on Debian, only on mono 4.2.1 or whether it is limited by some other environmental factor I did not make a pull request.

**Comment by decriptor** [comment]
I believe with commit 497c935 this should be fixed now.
