### ISSUE TITLE
Tag control provides misleading drag/drop indications

### ISSUE THREAD

**Issue by cizma** [mono/f-spot#65]
It is possible to reorganize tags by drag/drop.
In this way, user can move one tag to be re-parented under a different parent.

While in process of drag, there are GUI indications that dragged tag can be dropped in between two tags (see screenshot). This would make it possible to reorder sibling tags manually.

![drop_between_items](https://cloud.githubusercontent.com/assets/17114704/13364309/68faff3c-dcce-11e5-94a4-2e1ba1864a59.jpg)

Sibling tags are ordered according to property `Tag::SortPriority`, and then alphabetically in case `Tag::SortPriority` values are the same. Initial value of `Tag::SortPriority` property for all user created tags is `0`.

The problem is that `Tag::SortPriority` property is never updated after drop, so no matter where item is dropped it is always sorted alphabetically among all sibling tags (all have value `0`).

Only default tags (Favorites, Hidden, People, ...) have this property set because they are created programatically by application.

There are couple of possible courses of action:

##### Remove possibility to reorder tags using drag/drop

By removing following code segment from `TagSelectionWidget::HandleDragMotion`, it will no longer be possible to drop tag between two rows:

```csharp
// Tags can be dropped before, after, or into another tag
if (args.Context.Targets[0].Name == "application/x-fspot-tags") {
  Gdk.Rectangle rect = GetCellArea(path, Columns[0]);
  double vpos = Math.Abs(rect.Y - args.Y) / (double)rect.Height;
  if (vpos < 0.2) {
    position = TreeViewDropPosition.Before;
  } else if (vpos > 0.8) {
    position = TreeViewDropPosition.After;
  }
}
```

All tags will be alphabetically ordered.

##### Implement only manually ordered tags

* When new tag is added it is automatically added as the last child of node and its' `Tag::SortPriority` property is set accordingly.
* During drag/drop and tag deletion `Tag::SortPriority` properties of all sibling tags are updated so that they always reflect current position of a tag.

In this scenario name of the tag will never have an effect on item position because `Tag::SortPriority` properties of all siblings will be unique.

##### Implement full support for reordering of tags

`Tag::SortPriority` property should be updated on drop.
I haven't tested this behavior of Tag tree. We might end up with behavior that is confusing to user because of complex interaction of `Tag::SortPriority` property that can be any integer number.

Couple of discussion points:
* Do we always keep `Tag::SortPriority` as incremental number? If we allow manual sorting, we might consider exposing this value to user so he might assign some specific value to one tag. That way he can have one tag with `Tag::SortPriority` value of 1000 that will always keep last position.
* How to restore alphabetical ordering once manual order was created?
* What is `Tag::SortPriority` value of a newly created tag? Currently it is `0` and all tags with same value are sorted alphabetically among themselves.
* If we drag any item in a group with `Tag::SortPriority == 0`, we should update `Tag::SortPriority` properties on all of them. In case of screenshot we would need to update `Tag::SortPriority` of all tags in order to keep `Item 3` in between `Item 1` and `Item 2`.

###### Possible solution

* New tags are created with `Tag::SortPriority = 0` in case it is the first tag in group or if all other tags have `Tag::SortPriority == 0`.
* If there already exists a tag in a group with `Tag::SortPriority !=0`, than new tag will go to last place and it's `Tag::SortPriority` property will be set accordingly
* Whenever a tag is deleted or reordered, we update `Tag::SortPriority` properties on all sibling tags to keep them reflect their position in a group

In this case we would have alphabetically sorted tags if user didn't do any manual ordering, and manual sorting in case any reorder has been done inside a tag group.

#### Personal take on the problem

I would prefer to avoid last solution.
Combination of both alphabetical sorting and manual reordering might get confusing to users. I think we should choose either alphabetical sorting or manual ordering for all user created tags.

**Comment by dkoeb** [comment]
I think it's a good idea to deactivate the reordering indicator at least for now, as long as it has no effect.
Personally, I never had the need to sort tags other than alphabetically. Exposing the priority field directly to the user is not a good idea, imho. It adds unnecessary complexity.

**Comment by genterminl** [comment]
I'd like to keep the ability to order tags as an option.  I can see having a large number of tags in some group, but have only a few I'm working on actively, and that would be easier to find than having to search through the longer list.  However, given the difficulties, it is reasonable to disable for now, and leave it as a low priority, wish-list type item for future development.  Perhaps someone can eventually come up with an interface that is not likely to confuse a user - maybe something like color coding or highlighting any tags that are out of their default (alpha) search order.
