### ISSUE TITLE
cant import jpg

### ISSUE THREAD

**Issue by codingdave** [mono/f-spot#69]
When trying to import the following photo 
![dsc_1725](https://cloud.githubusercontent.com/assets/3075641/14545526/e9db5d80-029f-11e6-8b9e-2f431bf54715.JPG)
this is happening
![bildschirmfoto vom 2016-04-15 00-24-04](https://cloud.githubusercontent.com/assets/3075641/14545670/8bbd95aa-02a0-11e6-916e-77bf008b7b82.png)

I tried to dig to the issue but failed.

**Comment by dkoeb** [comment]
The metadata in the file is corrupt. Either your camera or the transfer to your computer broke it. You could look for a tool to fix/remove the metadata from the file and retry the import. F-spot does not have the means to fix this right now.

**Comment by codingdave** [comment]
This file once was successfully imported by the last f-spot that came with
Ubuntu so it would be a regression. I also think F-Spot should be robust,
this is why I decided to share this image. Unfortunately I wasnt able to
fix the code myself.
I know that I can easily fix the exif tags and then the problem is
resolved. However, I just hope that I can contribute to a more robust
f-spot version by sharing this image.

2016-04-20 20:30 GMT+02:00 dkoeb <notifications@github.com>:

**Comment by dkoeb** [comment]
That's interesting. If the picture was successfully imported in an earlier version of f-spot I assume that taglib-sharp is to blame. This library was updated a few months ago and is used in f-spot for metadata parsing.
I agree that it would be nice if f-spot would still import such images in a sane way. Nevertheless I already consider f-spot robust in this regard as it did not crash but report the image as corrupt.
Thanks for reporting and sharing the image!

**Comment by codingdave** [comment]
Fyi: using the taglib-sharp that comes with f-spot.git I get hundreds of import errors. Thats why I am using  b9f275b7355ac2b71fa2b93b4b1017f5ef0e44ae from their github repo. So I only have one image failing during the import.

**Comment by cizma** [comment]
I am not sure if the real problem is in taglib library.

If you look at the attached file using exiftool you will see some warnings during parsing of metadata:
`$ exiftool -a e9db5d80-029f-11e6-8b9e-2f431bf54715.JPG`

After using exiftool to try to fix the errors I was able to import the image:
`$ exiftool -exif:all= -tagsfromfile @ -all:all -unsafe e9db5d80-029f-11e6-8b9e-2f431bf54715.JPG`

It could be that files were bad from the start and it just happens that new version of library is stricter during parsing and throws and exception.

**Comment by codingdave** [comment]
I agree. Among all the 86 failing jpgs this one fails because of the damaged exif information. Thank you. 
In the same matter I wanted to continue with the other missing imports. However, they seem to have good exif information.
Like stated above I once was able to import them with another taglib revision. I tried to reproduce that but failed. I attached one failing example image. 

![52](https://cloud.githubusercontent.com/assets/3075641/15156103/bfb3b034-16e5-11e6-9600-574cdaf23f26.jpg)

**Comment by codingdave** [comment]
Many if not all images that fail to being imported are from a Sony cam. So I followed this trace. 
The error is that I get a System.Overflow exception in the taglib library. This happens directly after taglib/IFD/IFDReader.cs:858 specifically treats the sony header. I dont completely understand what should happen in the code shown below but I recognize that the type parameter is lost in that function. Also a IFDReader is initiated which seem to be unused. So for me it looks like there is no functionality:

if (header.StartsWith (SONY_HEADER)) {
IFDReader reader = new IFDReader (file, is_bigendian, ifd_structure, base_offset, offset + 12, max_offset);
reader.ReadIFD (base_offset, offset + 12, max_offset);
return new MakernoteIFDEntry (tag, ifd_structure, MakernoteType.Sony, SONY_HEADER, 12, true, null);
}

Since I doubt that code I commented it out. It looks like for now I can import all my files:

if (header.StartsWith (SONY_HEADER)) {
// IFDReader reader = new IFDReader (file, is_bigendian, ifd_structure, base_offset, offset + 12, max_offset);
// reader.ReadIFD (base_offset, offset + 12, max_offset);
return new MakernoteIFDEntry (tag, ifd_structure, MakernoteType.Sony, SONY_HEADER, 12, true, null);
}

**Comment by decriptor** [comment]
@codingdave can you create an issue on github.com/mono/taglib-sharp with that information and add me to it? Also, if you can attach an image with the problem that works after commenting out those lines that'd be very helpful.
if you can't add me to the issue, can you put it in the comments here too?

**Comment by codingdave** [comment]
@decriptor on https://github.com/mono/taglib-sharp I cannot find an issues tab and such cannot create that issue. 

> Also, if you can attach an image with the problem that works after commenting out those lines that'd be very helpful.

Unfortunately I cannot reproduce my hacks from that time. I will go baby steps and when I find the time try to reproduce it and have it well documented.

**Comment by decriptor** [comment]
@codingdave I just enabled `issues` on taglib-sharp. Not sure why it wasn't enabled already.

**Comment by decriptor** [comment]
@codingdave Do you want to submit a PR to bump taglib-sharp to pull in this fix?

**Comment by codingdave** [comment]
@decriptor  im confused: I did the PR for taglib-sharp and it was merged into taglib-sharp. Since it is a submodule of f-spot i was hoping that the merge will end up in f-spot. Is there something left to do on my side?

**Comment by decriptor** [comment]
submodules point at a specific commit. We need to bump which commit it is looking at. I've done that here -> https://github.com/mono/f-spot/commit/91d6141ab02f40884d7371ce67c050612c7bda53

**Comment by decriptor** [comment]
submodules point at a specific commit. We need to bump which commit it is looking at. I've done that here -> https://github.com/mono/f-spot/commit/91d6141ab02f40884d7371ce67c050612c7bda53

**Comment by codingdave** [comment]
okay, thank you. f-spot works now for my cases.

**Comment by decriptor** [comment]
Very happy to hear that
