### ISSUE TITLE
How to draw a circle on a given shapefile or map using sharpmap?

### ISSUE THREAD

**Issue by Shree1100** [mono/f-spot#73]
Can Someone please tell me how to draw a circle on a given layer or on a shapefile?Is there any way to draw a circle knowing the center point and the radius?Being a beginner i have very less knowledge of this part.Also if u can tell me if it is necessary to add a layer on existing layer while drawing a circle or we can draw it on the same existing layer of the shapefile using Sharpmap only?Thanks

**Comment by genterminl** [comment]
What does this have to do with f-spot?  Did you post this in the wrong place?

**Comment by dkoeb** [comment]
Closed as not related to f-spot.
